services:
  - type: web
    name: event-manager-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
